SELECT EMPLOYEE_NO, EMPLOYEE_NAME, DEPARTMENT_CODE, DEPARTMENT_HIGH_CODE, DEPARTMENT_TITLE, POSITION_CODE, POSITION_TITLE, EMPLOYEE_PHOTO, EMPLOYEE_ID
    	FROM EMPLOYEE
    		JOIN DEPARTMENT USING(DEPARTMENT_CODE)
            JOIN POSITION USING(POSITION_CODE)
        WHERE EMPLOYEE_RESIGNATION_DAY IS NULL
        ORDER BY EMPLOYEE_NO;