SELECT * FROM EMPLOYEE JOIN DEPARTMENT USING(DEPARTMENT_CODE);
COMMIT;
SELECT * FROM commuting;
ALTER TABLE COMMUTING MODIFY COMMUTING_LEAVE_WORK_TIME DATE;

SELECT COUNT(*) FROM COMMUTING
		JOIN EMPLOYEE USING(EMPLOYEE_NO)
    	WHERE EMPLOYEE_ID = 'ceokim'
    		  AND 
    		  COMMUTING_GO_WORK_TIME BETWEEN TO_DATE(2024 || '-' || 6 || '-01', 'YYYY-MM-DD')
   			  					     AND LAST_DAY(TO_DATE(2024 || '-' || 6 || '-01', 'YYYY-MM-DD'));