SELECT
	COUNT(CASE WHEN APPROVER_STATUS IS NULL THEN 1 END) AS approvalWait,
	COUNT(CASE WHEN APPROVER_STATUS = 1 AND APPROVAL_STATUS = 2 THEN 1 END) AS approvalProcess,
	COUNT(CASE WHEN APPROVER_STATUS IS NULL AND APPROVAL_STATUS = 1 THEN 1 END) AS approvalPending,
	COUNT(CASE WHEN APPROVER_STATUS = 3 THEN 1 END) AS approvalComplete
FROM APPROVAL a
	JOIN APPROVER b USING(APPROVAL_NO)
WHERE b.EMPLOYEE_NO = 1000;

INSERT INTO APPROVAL VALUES('2-2024-0724-'||LPAD(SEQ_APPROVAL.NEXTVAL,3,'0'), 1000, TO_DATE('2024-07-24'), TO_DATE('2024-10-24'), '휴가간다요', '휴가가니까 연락하지마', 2, 'A');

CREATE SEQUENCE SEQ_EXPENDITURE_ITEM;

SELECT * FROM APPROVAL;
SELECT * FROM APPROVER;
SELECT * FROM APPROVAL_ATT;
SELECT * FROM BUSINESS_TRIP_FORM btf ;
SELECT * FROM BUSINESS_TRIP_PARTNER btp ;

SELECT * FROM APPROVAL a JOIN APPROVER b USING(APPROVAL_NO) WHERE b.EMPLOYEE_NO = 1000;

INSERT INTO APPROVER VALUES(SEQ_APPROVER.NEXTVAL, '2-2024-0724-003', 1001, 1, TO_DATE('2024-07-24'), NULL, 1);
INSERT INTO APPROVER VALUES(SEQ_APPROVER.NEXTVAL, '2-2024-0724-003', 1000, null, TO_DATE('2024-07-24'), NULL, 2);

SELECT *
FROM APPROVAL a
	JOIN EMPLOYEE e ON a.EMPLOYEE_NO = e.EMPLOYEE_NO
	JOIN DEPARTMENT d ON e.DEPARTMENT_CODE = d.DEPARTMENT_CODE
	JOIN "POSITION" p ON e.POSITION_CODE = p.POSITION_CODE
	JOIN APPROVER r ON a.APPROVAL_NO = r.APPROVER_NO
WHERE r.EMPLOYEE_NO = 1000;

SELECT a.*, b.*, e.*, d.*, p.*
FROM APPROVAL a
JOIN APPROVER b ON a.APPROVAL_NO = b.APPROVAL_NO
JOIN EMPLOYEE e ON b.EMPLOYEE_NO = e.EMPLOYEE_NO
JOIN DEPARTMENT d ON e.DEPARTMENT_CODE = d.DEPARTMENT_CODE
JOIN POSITION p ON e.POSITION_CODE = p.POSITION_CODE
WHERE a.APPROVAL_NO IN (
    SELECT a.APPROVAL_NO
    FROM APPROVAL a
    JOIN APPROVER b ON a.APPROVAL_NO = b.APPROVAL_NO
    WHERE b.EMPLOYEE_NO = 1000
)
ORDER BY a.APPROVAL_NO DESC;
UPDATE APPROVAL SET APPROVAL_STATUS = 3 WHERE APPROVAL_NO='2-2024-0724-002';
UPDATE APPROVER SET APPROVER_STATUS = 4 WHERE APPROVAL_NO='2-2024-0724-003' AND EMPLOYEE_NO=1001;
COMMIT;


SELECT
    (SELECT COUNT(DISTINCT a.APPROVAL_NO)
     FROM APPROVAL a
		JOIN APPROVER b ON a.APPROVAL_NO = b.APPROVAL_NO
	 WHERE b.EMPLOYEE_NO = 1000 -- 특정 사원 번호
	 AND b.APPROVER_STATUS = 4 -- 결재자 상태가 '대기'
	 AND (
	    -- 첫 번째 결재자일 경우
	    b.APPROVER_LEVEL = 1
	    OR
	    -- n번째 결재자인 경우
	    (
	        EXISTS (
	            SELECT 1
	            FROM APPROVER s
	            WHERE s.APPROVAL_NO = b.APPROVAL_NO
	            AND s.APPROVER_LEVEL = b.APPROVER_LEVEL - 1
	            AND s.APPROVER_STATUS = 1 -- 이전 결재자가 '승인' 상태일 경우
	        )
	        AND b.APPROVER_STATUS = 4 -- 현재 결재자 상태가 '대기'
	    )
	)) AS waitCount,
    (SELECT COUNT(DISTINCT a.APPROVAL_NO)
	 FROM APPROVAL a
		JOIN APPROVER b ON a.APPROVAL_NO = b.APPROVAL_NO
	 WHERE b.EMPLOYEE_NO = 1000 -- 특정 사원 번호
	 AND b.APPROVER_STATUS = 1 -- 결재자 상태가 '승인'
	 AND a.APPROVAL_STATUS = 2
	) AS processCount,
    (SELECT COUNT(DISTINCT s1.APPROVAL_NO)
     FROM APPROVER s1
     JOIN APPROVER s2 ON s1.APPROVAL_NO = s2.APPROVAL_NO
     WHERE s2.EMPLOYEE_NO = 1000
     AND s2.APPROVER_STATUS = 4
     AND EXISTS (
         SELECT 1
         FROM APPROVER s3
         WHERE s3.APPROVAL_NO = s1.APPROVAL_NO
         AND s3.APPROVER_STATUS = 4
         AND s3.APPROVER_LEVEL < s2.APPROVER_LEVEL
     )) AS pendingCount,
    (SELECT COUNT(*)
     FROM APPROVAL a JOIN APPROVER b ON a.APPROVAL_NO = b.APPROVAL_NO
	 WHERE APPROVAL_STATUS = 3
	 AND b.EMPLOYEE_NO = 1000
	 ) AS completeCount
FROM dual;

-- 결재 완료
SELECT COUNT(DISTINCT a.APPROVAL_NO)
FROM APPROVAL a
	JOIN APPROVER b ON a.APPROVAL_NO = b.APPROVAL_NO
WHERE APPROVAL_STATUS = 3 AND b.EMPLOYEE_NO = 1000;


-- 결재 대기
SELECT COUNT(DISTINCT a.APPROVAL_NO)
FROM APPROVAL a
	JOIN APPROVER b ON a.APPROVAL_NO = b.APPROVAL_NO
WHERE b.EMPLOYEE_NO = 1000 -- 특정 사원 번호
	AND b.APPROVER_STATUS = 4 -- 결재자 상태가 '대기'
	AND (
		    -- 첫 번째 결재자일 경우
		    b.APPROVER_LEVEL = 1
		    OR
		    -- n번째 결재자인 경우
	    (
	        EXISTS (
	            SELECT 1
	            FROM APPROVER s
	            WHERE s.APPROVAL_NO = b.APPROVAL_NO
		            AND s.APPROVER_LEVEL = b.APPROVER_LEVEL - 1
		            AND s.APPROVER_STATUS = 1 -- 이전 결재자가 '승인' 상태일 경우
	        )
	        AND b.APPROVER_STATUS = 4 -- 현재 결재자 상태가 '대기'
	    )
	);


-- 결재 진행
SELECT COUNT(DISTINCT a.APPROVAL_NO)
FROM APPROVAL a
	JOIN APPROVER b ON a.APPROVAL_NO = b.APPROVAL_NO
WHERE b.EMPLOYEE_NO = 1000 -- 특정 사원 번호
	AND b.APPROVER_STATUS = 1 -- 결재자 상태가 '승인'
	AND a.APPROVAL_STATUS = 2; -- 결재문서 상태가 '진행'



-- 결재 예정
SELECT COUNT(DISTINCT a.APPROVAL_NO)
FROM APPROVAL a
	JOIN APPROVER b ON a.APPROVAL_NO = b.APPROVAL_NO
WHERE b.EMPLOYEE_NO = 1000 -- 특정 사원 번호
	AND b.APPROVER_STATUS = 4 -- 내 결재 상태가 '대기'
	AND a.APPROVAL_STATUS IN (1, 2) -- 결재문서 상태가 '대기' 또는 '진행'
	AND EXISTS (
	    SELECT 1
	    FROM APPROVER s
	    WHERE s.APPROVAL_NO = b.APPROVAL_NO
	    AND s.APPROVER_STATUS = 4 -- 전 결재차례에 '대기' 상태 존재
	    AND s.APPROVER_LEVEL < b.APPROVER_LEVEL -- 전 결재차례
	);
