SELECT *
FROM APPROVAL a
	JOIN EMPLOYEE e ON a.EMPLOYEE_NO = e.EMPLOYEE_NO
	JOIN DEPARTMENT d ON e.DEPARTMENT_CODE = d.DEPARTMENT_CODE
	JOIN POSITION p ON e.POSITION_CODE = p.POSITION_CODE
	JOIN VACATION_FORM v ON a.APPROVAL_NO = v.APPROVAL_NO
WHERE a.APPROVAL_STATUS = 3
	;