SELECT * FROM PROJECT;

ALTER TABLE PROJECT
MODIFY PROJECT_STATUS DEFAULT '진행중';

SELECT * FROM DEPARTMENT d ;
SELECT DEPARTMENT_TITLE
FROM DEPARTMENT
START WITH DEPARTMENT_HIGH_CODE IS NULL
CONNECT BY PRIOR DEPARTMENT_CODE = DEPARTMENT_HIGH_CODE
ORDER SIBLINGS BY DEPARTMENT_TITLE;














SELECT * FROM DEPARTMENT;

SELECT * FROM employee;

SELECT * FROM APPROVAL;

SELECT * FROM OVERTIME_FORM;

SELECT a.*, e.employee_Name, d.department_TITLE
        FROM Approval a
        		JOIN Employee e ON a.employee_No = e.employee_No
        		JOIN Department d ON e.department_CODE = d.department_CODE
        ORDER BY a.approval_Draft_Date DESC;





INSERT INTO APPROVAL(APPROVAL_NO, APPROVAL_DRAFT_DATE, APPROVAL_DOC_PERIOD, APPROVAL_TITLE, APPROVAL_CONTENT, EMPLOYEE_NO)
VALUES(1, '2024-07-05', '2024-12-05', '출장 신청서', '7월 10일부터 7월 15일까지 서울 출장 예정입니다.', 1012);
INSERT INTO APPROVAL(APPROVAL_NO, APPROVAL_DRAFT_DATE, APPROVAL_DOC_PERIOD, APPROVAL_TITLE, APPROVAL_CONTENT, EMPLOYEE_NO)
VALUES(2, '2024-07-06', '2024-12-06', '휴가 신청서', '8월 1일부터 8월 5일까지 휴가를 신청합니다.', 1013);
INSERT INTO APPROVAL(APPROVAL_NO, APPROVAL_DRAFT_DATE, APPROVAL_DOC_PERIOD, APPROVAL_TITLE, APPROVAL_CONTENT, EMPLOYEE_NO)
VALUES(3, '2024-07-07', '2024-12-07', '초과 근무 신청서', '8월 10일 저녁 9시까지 초과 근무를 신청합니다.', 1014);
INSERT INTO APPROVAL(APPROVAL_NO, APPROVAL_DRAFT_DATE, APPROVAL_DOC_PERIOD, APPROVAL_TITLE, APPROVAL_CONTENT, EMPLOYEE_NO)
VALUES(4, '2024-07-08', '2024-12-08', '경비 지출 신청서', '6월 경비 지출 내역입니다.', 1015);
INSERT INTO APPROVAL(APPROVAL_NO, APPROVAL_DRAFT_DATE, APPROVAL_DOC_PERIOD, APPROVAL_TITLE, APPROVAL_CONTENT, EMPLOYEE_NO)
VALUES(5, '2024-07-09', '2024-12-09', '출퇴근 정정 신청서', '6월 출퇴근 기록을 정정합니다.', 1016);
