SELECT * FROM employee WHERE EMPLOYEE_NO = 1000;
SELECT * FROM commuting WHERE EMPLOYEE_NO =1000;
DELETE FROM commuting WHERE commuting_no=88;
SELECT * FROM commuting;
SELECT COMMUTING_GO_WORK_TIME, COMMUTING_LEAVE_WORK_TIME, COMMUTING_STATUS, COMMUTING_DATE
FROM COMMUTING JOIN EMPLOYEE USING(EMPLOYEE_NO)
WHERE EMPLOYEE_ID='ceokim' AND TRUNC(COMMUTING_DATE)=TRUNC(SYSDATE);

SELECT * FROM DEPARTMENT;

SELECT d.DEPARTMENT_TITLE, hd.DEPARTMENT_TITLE AS DEPARTMENT_HIGH_TITLE
FROM DEPARTMENT d
LEFT JOIN DEPARTMENT hd ON d.DEPARTMENT_HIGH_CODE = hd.DEPARTMENT_CODE
START WITH d.DEPARTMENT_HIGH_CODE IS NULL
		CONNECT BY PRIOR d.DEPARTMENT_CODE = d.DEPARTMENT_HIGH_CODE
		ORDER SIBLINGS BY d.DEPARTMENT_TITLE;

SELECT
	d.DEPARTMENT_CODE,
    d.DEPARTMENT_TITLE,
    h.DEPARTMENT_TITLE AS DEPARTMENT_HIGH_TITLE,
    e.EMPLOYEE_NAME AS DEPARTMENT_HEAD_NAME,
    CASE
        WHEN d.DEPARTMENT_HIGH_CODE = 1 THEN
            (SELECT COUNT(*)
             FROM EMPLOYEE e2
             JOIN DEPARTMENT d2 ON e2.DEPARTMENT_CODE = d2.DEPARTMENT_CODE
             WHERE d2.DEPARTMENT_HIGH_CODE = d.DEPARTMENT_CODE)
        ELSE
            (SELECT COUNT(*)
             FROM EMPLOYEE e2
             WHERE e2.DEPARTMENT_CODE = d.DEPARTMENT_CODE)
    END AS TOTAL_DEPARTMENT_COUNT
FROM
    DEPARTMENT d
LEFT JOIN
    DEPARTMENT h ON d.DEPARTMENT_HIGH_CODE = h.DEPARTMENT_CODE
LEFT JOIN
    EMPLOYEE e ON d.DEPARTMENT_CODE = e.DEPARTMENT_CODE AND e.POSITION_CODE = 2
WHERE d.DEPARTMENT_TITLE LIKE '개발%'
START WITH d.DEPARTMENT_HIGH_CODE IS NULL
		CONNECT BY PRIOR d.DEPARTMENT_CODE = d.DEPARTMENT_HIGH_CODE
		ORDER SIBLINGS BY d.DEPARTMENT_TITLE;


SELECT * FROM employee WHERE DEPARTMENT_CODE = 6;

SELECT *
FROM EMPLOYEE
	JOIN DEPARTMENT USING(DEPARTMENT_CODE)
	JOIN POSITION USING(POSITION_CODE)
WHERE TRUNC(EMPLOYEE_HIRE_DATE) >= TRUNC(TO_DATE('2024-07-01'));

SELECT COUNT(*)
       	FROM EMPLOYEE
       		JOIN DEPARTMENT USING(DEPARTMENT_CODE)
       		JOIN POSITION USING(POSITION_CODE)
       	 WHERE  TRUNC(EMPLOYEE_HIRE_DATE) >= TRUNC(to_date('07/01/2024 00:00:00', 'mm/dd/yyyy hh24:mi:ss'));



SELECT * FROM commuting WHERE employee_no=1000;
SELECT COMMUTING_DATE, COMMUTING_GO_WORK_TIME, COMMUTING_LEAVE_WORK_TIME, COMMUTING_STATUS
		FROM COMMUTING
		WHERE EMPLOYEE_NO=1000
		      AND (
		      		COMMUTING_GO_WORK_TIME >= TO_DATE(2024 || '-' || 7 || '-01', 'YYYY-MM-DD')
        	  		AND COMMUTING_GO_WORK_TIME < TO_DATE(2024 || '-' || 7 || '-01', 'YYYY-MM-DD') + INTERVAL '1' MONTH
        	      )
        	  OR TRUNC(COMMUTING_DATE) = TRUNC(SYSDATE)
        ORDER BY COMMUTING_GO_WORK_TIME DESC;

SELECT COMMUTING_DATE, COMMUTING_GO_WORK_TIME, COMMUTING_LEAVE_WORK_TIME, COMMUTING_STATUS
		FROM COMMUTING
		WHERE EMPLOYEE_NO=1000
		  AND COMMUTING_DATE >= TO_DATE(2024 || '-' || '7' || '-01', 'YYYY-MM-DD')
          AND COMMUTING_DATE < TO_DATE(2024 || '-' || '7' || '-01', 'YYYY-MM-DD') + INTERVAL '1' MONTH
        ORDER BY COMMUTING_DATE DESC;

SELECT c.*, d.DEPARTMENT_TITLE, p.POSITION_TITLE, e.EMPLOYEE_NAME
FROM
	EMPLOYEE e
	LEFT JOIN COMMUTING c ON e.EMPLOYEE_NO = c.EMPLOYEE_NO
	JOIN DEPARTMENT d ON e.DEPARTMENT_CODE = d.DEPARTMENT_CODE
	JOIN POSITION p ON e.POSITION_CODE = p.POSITION_CODE
WHERE
	e.EMPLOYEE_NAME LIKE '%김%'
	AND TRUNC(c.COMMUTING_DATE) = '2024-07-18'
	AND d.DEPARTMENT_CODE = 2
	AND c.COMMUTING_STATUS = '결근'
ORDER BY
	c.COMMUTING_DATE DESC;

