SELECT * FROM department;
COMMIT;
DELETE FROM department WHERE department_code=12;

SELECT * FROM employee WHERE employee_id='user01';
DELETE FROM EMPLOYEE WHERE EMPLOYEE_NO=1062;
COMMIT;



SELECT c.*, e.EMPLOYEE_NO, d.DEPARTMENT_TITLE, p.POSITION_TITLE, e.EMPLOYEE_NAME 
FROM COMMUTING c
	JOIN EMPLOYEE e ON c.EMPLOYEE_NO = e.EMPLOYEE_NO 
	JOIN DEPARTMENT d ON e.DEPARTMENT_CODE = d.DEPARTMENT_CODE 
	JOIN POSITION p on e.POSITION_CODE = p.POSITION_CODE;