SELECT	a.*
				, e.*
				, dept.*
				, att.*
				, ap.APPROVER_LEVEL AS APPROVER_APPROVER_LEVEL
				, ap.APPROVER_STATUS AS APPROVER_APPROVER_STATUS
				, ap.APPROVER_DATE AS APPROVER_APPROVER_DATE
				, rf.REFERENCE_NO
				, rf.REFERENCE_TYPE
				, ref_emp.EMPLOYEE_NO AS REFERENCE_EMPLOYEE_NO
				, ref_emp.EMPLOYEE_NAME AS REFERENCE_EMPLOYEE_NAME
				, ref_dept.DEPARTMENT_TITLE AS REFERENCE_DEPARTMENT_TITLE
				, ref_pos.POSITION_TITLE AS REFERENCE_POSITION_TITLE
				, approver.EMPLOYEE_NO AS APPROVER_EMPLOYEE_NO
				, approver.EMPLOYEE_NAME AS APPROVER_EMPLOYEE_NAME
				, approverdept.DEPARTMENT_TITLE AS APPROVER_DEPARTMENT_TITLE
				, approverpos.POSITION_CODE AS APPROVER_POSITION_CODE
				, approverpos.POSITION_TITLE AS APPROVER_POSITION_TITLE
	            , btf.*
	            , btp.*
	            FROM APPROVAL a
	                LEFT JOIN BUSINESS_TRIP_FORM btf ON btf.APPROVAL_NO = a.APPROVAL_NO
	                LEFT JOIN BUSINESS_TRIP_PARTNER btp ON btp.BUSINESS_TRIP_FORM_NO = btf.BUSINESS_TRIP_FORM_NO
    	LEFT JOIN
    		EMPLOYEE e ON e.EMPLOYEE_NO=a.EMPLOYEE_NO
		JOIN
			DEPARTMENT dept ON dept.DEPARTMENT_CODE=e.DEPARTMENT_CODE
		LEFT JOIN
		    APPROVAL_ATT att ON att.APPROVAL_NO=a.APPROVAL_NO
		LEFT JOIN
		    REFERENCE rf ON rf.APPROVAL_NO=a.APPROVAL_NO
		LEFT JOIN
			APPROVER ap ON ap.APPROVAL_NO=a.APPROVAL_NO
		LEFT JOIN
		    EMPLOYEE approver ON approver.EMPLOYEE_NO=ap.EMPLOYEE_NO
		LEFT JOIN
		    DEPARTMENT approverdept ON approverdept.DEPARTMENT_CODE=approver.DEPARTMENT_CODE
		LEFT JOIN
			POSITION approverpos ON approverpos.POSITION_CODE=approver.POSITION_CODE
		LEFT JOIN
		    EMPLOYEE ref_emp ON ref_emp.EMPLOYEE_NO=rf.EMPLOYEE_NO
		LEFT JOIN
		    DEPARTMENT ref_dept ON ref_dept.DEPARTMENT_CODE=ref_emp.DEPARTMENT_CODE
		LEFT JOIN
			POSITION ref_pos ON ref_pos.POSITION_CODE=ref_emp.POSITION_CODE
		WHERE
		    a.APPROVAL_NO='5-2024-0805-040'
		ORDER BY a.APPROVAL_DATE DESC;

	SELECT * FROM BUSINESS_TRIP_PARTNER btp WHERE BUSINESS_TRIP_FORM_NO = 7;

SELECT	a.*
				, e.*
				, dept.*
				, att.*
				, ap.APPROVER_LEVEL AS APPROVER_APPROVER_LEVEL
				, ap.APPROVER_STATUS AS APPROVER_APPROVER_STATUS
				, ap.APPROVER_DATE AS APPROVER_APPROVER_DATE
				, rf.REFERENCE_NO
				, rf.REFERENCE_TYPE
				, ref_emp.EMPLOYEE_NO AS REFERENCE_EMPLOYEE_NO
				, ref_emp.EMPLOYEE_NAME AS REFERENCE_EMPLOYEE_NAME
				, ref_dept.DEPARTMENT_TITLE AS REFERENCE_DEPARTMENT_TITLE
				, ref_pos.POSITION_TITLE AS REFERENCE_POSITION_TITLE
				, approver.EMPLOYEE_NO AS APPROVER_EMPLOYEE_NO
				, approver.EMPLOYEE_NAME AS APPROVER_EMPLOYEE_NAME
				, approverdept.DEPARTMENT_TITLE AS APPROVER_DEPARTMENT_TITLE
				, approverpos.POSITION_CODE AS APPROVER_POSITION_CODE
				, approverpos.POSITION_TITLE AS APPROVER_POSITION_TITLE
	            , btf.*
	            , btp.EMPLOYEE_NO AS BTP_EMPLOYEE_NO
	            , btpe.EMPLOYEE_NAME AS BTP_EMPLOYEE_NAME
	            FROM APPROVAL a
	                LEFT JOIN BUSINESS_TRIP_FORM btf ON btf.APPROVAL_NO = a.APPROVAL_NO
	                LEFT JOIN BUSINESS_TRIP_PARTNER btp ON btp.BUSINESS_TRIP_FORM_NO = btf.BUSINESS_TRIP_FORM_NO
	                JOIN EMPLOYEE btpe ON btp.EMPLOYEE_NO = btpe.EMPLOYEE_NO
    	LEFT JOIN
    		EMPLOYEE e ON e.EMPLOYEE_NO=a.EMPLOYEE_NO
		JOIN
			DEPARTMENT dept ON dept.DEPARTMENT_CODE=e.DEPARTMENT_CODE
		LEFT JOIN
		    APPROVAL_ATT att ON att.APPROVAL_NO=a.APPROVAL_NO
		LEFT JOIN
		    REFERENCE rf ON rf.APPROVAL_NO=a.APPROVAL_NO
		LEFT JOIN
			APPROVER ap ON ap.APPROVAL_NO=a.APPROVAL_NO
		LEFT JOIN
		    EMPLOYEE approver ON approver.EMPLOYEE_NO=ap.EMPLOYEE_NO
		LEFT JOIN
		    DEPARTMENT approverdept ON approverdept.DEPARTMENT_CODE=approver.DEPARTMENT_CODE
		LEFT JOIN
			POSITION approverpos ON approverpos.POSITION_CODE=approver.POSITION_CODE
		LEFT JOIN
		    EMPLOYEE ref_emp ON ref_emp.EMPLOYEE_NO=rf.EMPLOYEE_NO
		LEFT JOIN
		    DEPARTMENT ref_dept ON ref_dept.DEPARTMENT_CODE=ref_emp.DEPARTMENT_CODE
		LEFT JOIN
			POSITION ref_pos ON ref_pos.POSITION_CODE=ref_emp.POSITION_CODE
		WHERE
		    a.APPROVAL_NO='5-2024-0805-040'
		ORDER BY a.APPROVAL_DATE DESC;

SELECT a.*     , e.*     , dept.*     , att.*     , ap.APPROVER_LEVEL AS APPROVER_APPROVER_LEVEL     , ap.APPROVER_STATUS AS APPROVER_APPROVER_STATUS     , ap.APPROVER_DATE AS APPROVER_APPROVER_DATE     , rf.REFERENCE_NO     , rf.REFERENCE_TYPE     , ref_emp.EMPLOYEE_NO AS REFERENCE_EMPLOYEE_NO     , ref_emp.EMPLOYEE_NAME AS REFERENCE_EMPLOYEE_NAME     , ref_dept.DEPARTMENT_TITLE AS REFERENCE_DEPARTMENT_TITLE     , ref_pos.POSITION_TITLE AS REFERENCE_POSITION_TITLE     , approver.EMPLOYEE_NO AS APPROVER_EMPLOYEE_NO     , approver.EMPLOYEE_NAME AS APPROVER_EMPLOYEE_NAME     , approverdept.DEPARTMENT_TITLE AS APPROVER_DEPARTMENT_TITLE     , approverpos.POSITION_CODE AS APPROVER_POSITION_CODE     , approverpos.POSITION_TITLE AS APPROVER_POSITION_TITLE                             , btf.*              , btp.*              , btpe.EMPLOYEE_NO AS BTP_EMPLOYEE_NO              , btpe.EMPLOYEE_NAME AS BTP_EMPLOYEE_NAME              , btped.DEPARTEMNT_TITLE AS BTP_DEPARTMENT_TITLE              , btpep.POSITION_TITLE AS BTP_POSITION_TITLE              FROM APPROVAL a                  LEFT JOIN BUSINESS_TRIP_FORM btf ON btf.APPROVAL_NO = a.APPROVAL_NO                  LEFT JOIN BUSINESS_TRIP_PARTNER btp ON btp.BUSINESS_TRIP_FORM_NO = btf.BUSINESS_TRIP_FORM_NO                  JOIN EMPLOYEE btpe ON btp.EMPLOYEE_NO = btpe.EMPLOYEE_NO                  JOIN POSITION btpep ON btpep.POSITION_CODE = btpe.POSITION_CODE                  JOIN DEPARTMENT btped ON btped.DEPARTMENT_CODE = btpe.DEPARTMENT_CODE                            LEFT JOIN       EMPLOYEE e ON e.EMPLOYEE_NO=a.EMPLOYEE_NO   JOIN    DEPARTMENT dept ON dept.DEPARTMENT_CODE=e.DEPARTMENT_CODE   LEFT JOIN       APPROVAL_ATT att ON att.APPROVAL_NO=a.APPROVAL_NO   LEFT JOIN       REFERENCE rf ON rf.APPROVAL_NO=a.APPROVAL_NO   LEFT JOIN    APPROVER ap ON ap.APPROVAL_NO=a.APPROVAL_NO   LEFT JOIN       EMPLOYEE approver ON approver.EMPLOYEE_NO=ap.EMPLOYEE_NO   LEFT JOIN       DEPARTMENT approverdept ON approverdept.DEPARTMENT_CODE=approver.DEPARTMENT_CODE   LEFT JOIN    POSITION approverpos ON approverpos.POSITION_CODE=approver.POSITION_CODE   LEFT JOIN       EMPLOYEE ref_emp ON ref_emp.EMPLOYEE_NO=rf.EMPLOYEE_NO   LEFT JOIN       DEPARTMENT ref_dept ON ref_dept.DEPARTMENT_CODE=ref_emp.DEPARTMENT_CODE   LEFT JOIN    POSITION ref_pos ON ref_pos.POSITION_CODE=ref_emp.POSITION_CODE   WHERE       a.APPROVAL_NO='5-2024-0805-040'   ORDER BY a.APPROVAL_DATE DESC;

SELECT	a.*
				, e.*
				, dept.*
				, att.*
				, ap.APPROVER_LEVEL AS APPROVER_APPROVER_LEVEL
				, ap.APPROVER_STATUS AS APPROVER_APPROVER_STATUS
				, ap.APPROVER_DATE AS APPROVER_APPROVER_DATE
				, rf.REFERENCE_NO
				, rf.REFERENCE_TYPE
				, ref_emp.EMPLOYEE_NO AS REFERENCE_EMPLOYEE_NO
				, ref_emp.EMPLOYEE_NAME AS REFERENCE_EMPLOYEE_NAME
				, ref_dept.DEPARTMENT_TITLE AS REFERENCE_DEPARTMENT_TITLE
				, ref_pos.POSITION_TITLE AS REFERENCE_POSITION_TITLE
				, approver.EMPLOYEE_NO AS APPROVER_EMPLOYEE_NO
				, approver.EMPLOYEE_NAME AS APPROVER_EMPLOYEE_NAME
				, approverdept.DEPARTMENT_TITLE AS APPROVER_DEPARTMENT_TITLE
				, approverpos.POSITION_CODE AS APPROVER_POSITION_CODE
				, approverpos.POSITION_TITLE AS APPROVER_POSITION_TITLE
	            , btf.*
	            , btp.*
	            , btpe.EMPLOYEE_NO AS BTP_EMPLOYEE_NO
	            , btpe.EMPLOYEE_NAME AS BTP_EMPLOYEE_NAME
	            , btped.DEPARTMENT_TITLE AS BTP_DEPARTMENT_TITLE
	            , btpep.POSITION_TITLE AS BTP_POSITION_TITLE
	            FROM APPROVAL a
	                LEFT JOIN BUSINESS_TRIP_FORM btf ON btf.APPROVAL_NO = a.APPROVAL_NO
	                LEFT JOIN BUSINESS_TRIP_PARTNER btp ON btp.BUSINESS_TRIP_FORM_NO = btf.BUSINESS_TRIP_FORM_NO
	                JOIN EMPLOYEE btpe ON btp.EMPLOYEE_NO = btpe.EMPLOYEE_NO
	                JOIN POSITION btpep ON btpep.POSITION_CODE = btpe.POSITION_CODE
	                JOIN DEPARTMENT btped ON btped.DEPARTMENT_CODE = btpe.DEPARTMENT_CODE
    	LEFT JOIN
    		EMPLOYEE e ON e.EMPLOYEE_NO=a.EMPLOYEE_NO
		JOIN
			DEPARTMENT dept ON dept.DEPARTMENT_CODE=e.DEPARTMENT_CODE
		LEFT JOIN
		    APPROVAL_ATT att ON att.APPROVAL_NO=a.APPROVAL_NO
		LEFT JOIN
		    REFERENCE rf ON rf.APPROVAL_NO=a.APPROVAL_NO
		LEFT JOIN
			APPROVER ap ON ap.APPROVAL_NO=a.APPROVAL_NO
		LEFT JOIN
		    EMPLOYEE approver ON approver.EMPLOYEE_NO=ap.EMPLOYEE_NO
		LEFT JOIN
		    DEPARTMENT approverdept ON approverdept.DEPARTMENT_CODE=approver.DEPARTMENT_CODE
		LEFT JOIN
			POSITION approverpos ON approverpos.POSITION_CODE=approver.POSITION_CODE
		LEFT JOIN
		    EMPLOYEE ref_emp ON ref_emp.EMPLOYEE_NO=rf.EMPLOYEE_NO
		LEFT JOIN
		    DEPARTMENT ref_dept ON ref_dept.DEPARTMENT_CODE=ref_emp.DEPARTMENT_CODE
		LEFT JOIN
			POSITION ref_pos ON ref_pos.POSITION_CODE=ref_emp.POSITION_CODE
		WHERE
		    a.APPROVAL_NO='5-2024-0805-040'
		ORDER BY a.APPROVAL_DATE DESC;
