SELECT * FROM PROJECT;

ALTER TABLE PROJECT
MODIFY PROJECT_STATUS DEFAULT '진행중';

SELECT * FROM DEPARTMENT d ;
SELECT DEPARTMENT_TITLE
FROM DEPARTMENT
START WITH DEPARTMENT_HIGH_CODE IS NULL
CONNECT BY PRIOR DEPARTMENT_CODE = DEPARTMENT_HIGH_CODE
ORDER SIBLINGS BY DEPARTMENT_TITLE;
