SELECT COMMUTING_GO_WORK_TIME, COMMUTING_LEAVE_WORK_TIME, COMMUTING_STATUS
FROM commuting
WHERE EMPLOYEE_NO=1000 AND COMMUTING_GO_WORK_TIME >= TO_DATE(#{year} || '-' || #{month} || '-01', 'YYYY-MM-DD')
        AND COMMUTING_GO_WORK_TIME < TO_DATE(#{year} || '-' || #{month} || '-01', 'YYYY-MM-DD') + INTERVAL '1' MONTH;

SELECT COMMUTING_GO_WORK_TIME, COMMUTING_LEAVE_WORK_TIME, COMMUTING_STATUS
FROM commuting
WHERE EMPLOYEE_NO=1000 AND COMMUTING_GO_WORK_TIME >= TO_DATE(2024 || '-' || '7' || '-01', 'YYYY-MM-DD')
        AND COMMUTING_GO_WORK_TIME < TO_DATE(2024 || '-' || '7' || '-01', 'YYYY-MM-DD') + INTERVAL '1' MONTH
ORDER BY COMMUTING_GO_WORK_TIME DESC;

COMMIT;

INSERT INTO COMMUTING VALUES(SEQ_COMMUTING.NEXTVAL, 1000, TO_DATE('2024-07-31'), '', '출근');

SELECT * FROM COMMUTING;

SELECT COUNT(*)
		FROM COMMUTING
		WHERE EMPLOYEE_NO=1000
		      AND COMMUTING_GO_WORK_TIME >= TO_DATE(2024 || '-' || '7' || '-01', 'YYYY-MM-DD')
        	  AND COMMUTING_GO_WORK_TIME < TO_DATE(2024 || '-' || '7' || '-01', 'YYYY-MM-DD') + INTERVAL '1' MONTH;